spring:
  datasource:
    url: jdbc:h2:~/main;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true
  config:
    import: classpath:data.yml
  sql:
    init:
      mode: always
