#spring:
#  profiles.active: test
#  sql.init.mode: always
#  datasource:
#     driver-class-name: com.mysql.cj.jdbc.Driver
#     url: ${url}
#     username: ${username}
#     password: ${password}
##    url: jdbc:h2:~/test;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
##    username: sa
##    h2.console.enabled: true
#  mvc.pathmatch.matching-strategy: ANT_PATH_MATCHER
#
#---
#
#spring.config.activate.on-profile: prod
#security.jwt.token:
#  secret-key: ${secret-key}
#  expire-length: ${jwt-validity}
#
#---
#
#spring.config.activate.on-profile: test
#security.jwt.token:
#  secret-key: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
#  expire-length: 3600000
#
